// using the Vue library's createApp method, we're telling Vue to create the app object...
const app = Vue.createApp({
  // inside, we can create Vue data, functions, component templates, etc...
  template: '<h2>This is a Vue.js template...</h2>'
})

// we're telling Vue to mount the app to the DOM element with the id of 'app'...
app.mount('#app')
